### ISSUE TITLE
Blender dont see addon

### ISSUE THREAD

**Issue by radi0n** [mantissa-/RandoMesh#2]
I use latest build of blender and it does not see Your addon.

**Comment by mantissa-** [comment]
Which build would that be?
RandoMesh only works with the 2.80 beta, so it won't load correctly in 2.79 or earlier.

I just tested the linux 2.80 daily build and it works fine here, any more info on your os and build are welcome.

**Comment by radi0n** [comment]
Latest 2.80 blender-2.80-532536bf52da-win64

**Comment by mantissa-** [comment]
You only need the .py file, installing the zip file doesn't work.
Just did it that way on Windows myself and everything works as expected.

**Comment by radi0n** [comment]
Its working now. Thanks for the addon!

**Comment by mantissa-** [comment]
Alright, good to know. Have fun!

**Comment by Stroopwafel1** [comment]
I also cannot see the addon when I installed it. I did it through the blender preferences and I also tried it putting the py file directly inside the addon folder. Any advice?

**Comment by JarneDK** [comment]
hey man I'm having the same problem here
When I try to install the .py file inside preferences my blender doesn't show it afterwards... is it possible that I have that problem because Blender is installed on my D: drive instead of C: ?

**Comment by Stroopwafel1** [comment]
The drive issue should not be a problem I think. I thought I fixed it when I just installed the zip file. Can't really remember though.

**Comment by JarneDK** [comment]
How do you install the zip file instead of the .py file? Bcs when i click the folder in preferences it goes straight inside?

**Comment by Stroopwafel1** [comment]
By clicking the .zip file and after that click on "Install addon from file".

**Comment by JarneDK** [comment]
it worked! thank you so much

**Comment by joeflamesfire** [comment]
Hi im using blender 2.92 I have installed the plugin but cant find it i extracted the zip file to my desktop, clicked on the  .py file and it showed it installed but if is I search for it, nothing turns up

![Capture2](https://user-images.githubusercontent.com/84875016/119722634-7393b880-be64-11eb-9ca2-355565a25250.JPG)
