### ISSUE TITLE
Got an error 

### ISSUE THREAD

**Issue by ArxFatalis23** [mantissa-/RandoMesh#6]
[
![unknown1233](https://user-images.githubusercontent.com/86523181/123514475-841d9580-d693-11eb-876b-dedd2ce0b8a5.png)
](url)

Got this error when pressing destroy mesh. Noticed it was already a problem and supposed to be fixed, but yeah idk.

**Comment by NeverConvex** [comment]
What version of Blender are you using? I think the patch @JensKrumsieck added uses `percent=` as the keyword for versions lower than 2.93.0:

https://github.com/mantissa-/RandoMesh/blob/41dccf91e254966ac47acd5a6b18a730d62b54a7/__init__.py#L195

I compared 2.83 to 2.93 https://github.com/mantissa-/RandoMesh/issues/3#issuecomment-861082600, but it's possible the keyword change happened before 2.93.

**Comment by NeverConvex** [comment]
Oh, the problem is probably that this is a typo:
```
                bpy.ops.mesh.select_random(percentage=pct, seed=randint(1,9999))
```
https://github.com/mantissa-/RandoMesh/blob/41dccf91e254966ac47acd5a6b18a730d62b54a7/__init__.py#L196

`percentage` should be `percent`. @JensKrumsieck was probably testing on `2.93.0` or higher so it didn't get flagged in testing

**Comment by NeverConvex** [comment]
Opened a small PR to patch it: https://github.com/mantissa-/RandoMesh/pull/7

**Comment by ArxFatalis23** [comment]
I'm using 2.92, will try to get the new version tho to see if it works then.

**Comment by ArxFatalis23** [comment]
Now it works, thank you!

**Comment by NeverConvex** [comment]
@mantissa- seemed to be quite busy based on the issue that preceded this one, but hopefully he's able to review the tiny new PR shortly. Just tagging him here to try make sure he saw this.

**Comment by mantissa-** [comment]
Wow only saw this now, sorry folks
